# #data encoding >> converting categorical columns into numeric
* Nominal/OHE(one hot encode)
* label and ordinal encoding
* Target guided ordinal encoding

# Nominal/OHE >> Binary vector for each of the categories
#example single, married, separated
#single: [1, 0, 0]
#married: [0, 1, 0]
#separated: [0, 0, 1]

In [12]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({"status": ["single", "married", "separated", "single", "married"]})

In [13]:
df

,status
0,single
1,married
2,separated
3,single
4,married


In [14]:
encoder = OneHotEncoder()

In [15]:
encoder

,categories,'auto'
,drop,None
,sparse_output,True
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,min_frequency,None
,max_categories,None
,feature_name_combiner,'concat'


In [16]:
encoded = encoder.fit_transform(df[['status']]).toarray()
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [17]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [18]:
encoder_df = pd.DataFrame(encoded , columns = encoder.get_feature_names_out())
encoder_df

,status_married,status_separated,status_single
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0


In [19]:
# if new data comes
encoder.transform([['single']]).toarray()

c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [20]:
pd.concat([df,encoder_df], axis = 1)

,status,status_married,status_separated,status_single
0,single,0.0,0.0,1.0
1,married,1.0,0.0,0.0
2,separated,0.0,1.0,0.0
3,single,0.0,0.0,1.0
4,married,1.0,0.0,0.0


In [21]:
import seaborn as sns 
df2 = sns.load_dataset('tips')
df2


,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [22]:
df2['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [23]:
day_encoder = OneHotEncoder()
day_encoder

,categories,'auto'
,drop,None
,sparse_output,True
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,min_frequency,None
,max_categories,None
,feature_name_combiner,'concat'


In [29]:
day_encoded = (day_encoder.fit_transform(df2[["day"]]).toarray())
day_encoded

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],


In [30]:
df_day_encoded = pd.DataFrame(day_encoded , columns = day_encoder.get_feature_names_out())
df_day_encoded

,day_Fri,day_Sat,day_Sun,day_Thur
0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0
...,...,...,...,...
239,0.0,1.0,0.0,0.0
240,0.0,1.0,0.0,0.0
241,0.0,1.0,0.0,0.0
242,0.0,1.0,0.0,0.0


In [31]:
pd.concat([df2,df_day_encoded], axis = 1)

,total_bill,tip,sex,smoker,day,time,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,Female,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,0.0,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,0.0,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0.0,1.0,0.0,0.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0.0,1.0,0.0,0.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0.0,1.0,0.0,0.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0.0,1.0,0.0,0.0


# label encoding >> assign unique label to the categories
# using map or using library

In [32]:
df

,status
0,single
1,married
2,separated
3,single
4,married


In [33]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [34]:
label_encoder.fit_transform(df[['status']])

c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [35]:
label_encoder.transform([["separated"]])

c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

# ordinal encoding

* High school : 1
* gradiate: 2
* post graduate: 3
* Phd: 4

In [36]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({"qualification": ["HS","GR", "PG", "PHD", "HS", "PHD"]})

In [37]:
df

,qualification
0,HS
1,GR
2,PG
3,PHD
4,HS
5,PHD


In [38]:
encoder = OrdinalEncoder(categories=[["HS", "GR", "PG", "PHD"]])

In [39]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [3.]])

In [40]:
# new data
encoder.transform([["PG"]])

c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

# Target guided ordinal encoding
* relationship with target variable
* A lot of unique categories
* replace the category with mean and median of respective group

In [41]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [42]:
df

,time,total_bill
0,lunch,120
1,breakfast,130
2,dinner,90
3,lunch,125
4,breakfast,150
5,dinner,190
6,lunch,160
7,breakfast,180
8,dinner,189


In [43]:
mean_price = df.groupby("time")['total_bill'].mean().to_dict()

In [44]:
df['time_encoded'] = df['time'].map(mean_price)
df

,time,total_bill,time_encoded
0,lunch,120,135.000000
1,breakfast,130,153.333333
2,dinner,90,156.333333
3,lunch,125,135.000000
4,breakfast,150,153.333333
5,dinner,190,156.333333
6,lunch,160,135.000000
7,breakfast,180,153.333333
8,dinner,189,156.333333


In [45]:
df = sns.load_dataset('tips')

In [46]:
df

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [53]:
mean_size = df.groupby('sex')['size'].mean().to_dict()
mean_size

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2684\2920813032.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_size = df.groupby('sex')['size'].mean().to_dict()


{'Male': 2.6305732484076434, 'Female': 2.4597701149425286}

In [54]:
df['sex_encoded'] = df['sex'].map(mean_size)
df

,total_bill,tip,sex,smoker,day,time,size,sex_encoded
0,16.99,1.01,Female,No,Sun,Dinner,2,2.459770
1,10.34,1.66,Male,No,Sun,Dinner,3,2.630573
2,21.01,3.50,Male,No,Sun,Dinner,3,2.630573
3,23.68,3.31,Male,No,Sun,Dinner,2,2.630573
4,24.59,3.61,Female,No,Sun,Dinner,4,2.459770
...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,2.630573
240,27.18,2.00,Female,Yes,Sat,Dinner,2,2.459770
241,22.67,2.00,Male,Yes,Sat,Dinner,2,2.630573
242,17.82,1.75,Male,No,Sat,Dinner,2,2.630573
